// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6KpzlvUUPokA2Tym8r5mIRvI2aEo8dU',
    appId: '1:764901058827:web:0a8eca822da3825dd31a0e',
    messagingSenderId: '764901058827',
    projectId: 'study-app-7a5b0',
    authDomain: 'study-app-7a5b0.firebaseapp.com',
    storageBucket: 'study-app-7a5b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VRjaWboMH2aC_Fr4ihi52XSe9DshaX4',
    appId: '1:764901058827:android:0228316e23e9c4dfd31a0e',
    messagingSenderId: '764901058827',
    projectId: 'study-app-7a5b0',
    storageBucket: 'study-app-7a5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqh3yLPF5-1IQtQzsiwbsecxayu0NVqo',
    appId: '1:764901058827:ios:e8e2db29b829bc1bd31a0e',
    messagingSenderId: '764901058827',
    projectId: 'study-app-7a5b0',
    storageBucket: 'study-app-7a5b0.appspot.com',
    iosClientId: '764901058827-1dcl8q2rifq8avhj4b64b950p6q1v45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGqh3yLPF5-1IQtQzsiwbsecxayu0NVqo',
    appId: '1:764901058827:ios:e8e2db29b829bc1bd31a0e',
    messagingSenderId: '764901058827',
    projectId: 'study-app-7a5b0',
    storageBucket: 'study-app-7a5b0.appspot.com',
    iosClientId: '764901058827-1dcl8q2rifq8avhj4b64b950p6q1v45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
